[project]
name = "ha-storybutton"
version = "0.1.0"
description = "Storybutton integration for Home Assistant"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "homeassistant==2024.12.5",
    "upnpclient",
]
