[project]
name = "ha-storybutton"
version = "0.1.0"
description = "Storybutton integration for Home Assistant"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "upnpclient",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "homeassistant==2024.12.5",
]
